### ISSUE TITLE
请问nextra v3的文档在哪里

### ISSUE THREAD

**Issue by zhangtao25** [pdsuwwz/nextjs-nextra-starter#36]
请问nextra v3的文档在哪里

**Comment by pdsuwwz** [comment]
@zhangtao25  你好，目前官网还没有放出 v3 文档，但官方仓库是有 v3 分支的，可参考对应的 issue 讨论：https://github.com/shuding/nextra/issues/1421

（如果你喜欢这个项目或发现有用，可以点右上角 [Star](https://github.com/pdsuwwz/nextjs-nextra-starter) 支持一下，谢谢 😃）

**Comment by pdsuwwz** [comment]
此 issue 已关闭。如有进一步问题，请重新打开或创建新 issue，谢谢。
