### ISSUE TITLE
如何新增页面并且显示在navBar？

### ISSUE THREAD

**Issue by noexpect9** [pdsuwwz/nextjs-nextra-starter#40]
请问下 如何新增顶部的导航栏呢 新增了一个frameworks 并未生效
![Uploading image.png…]()

**Comment by noexpect9** [comment]
<img width="426" alt="Snipaste_2024-11-22_14-58-48" src="https://github.com/user-attachments/assets/98139b33-0cdc-4603-93fa-b63949b11f89">
访问/frameworks 显示404

**Comment by pdsuwwz** [comment]
@noexpect9  你好，请尝试在对应的语言 (en/zh) 目录下创建文件夹，看是否生效。

**Comment by noexpect9** [comment]
这样是可以的。将创建的page显示到navbar 需要增加额外的配置吗？
![image](https://github.com/user-attachments/assets/406e2ec7-d441-4697-9e60-67b13d3a39e8)

**Comment by pdsuwwz** [comment]
是的，还需要配置下 `_meta.ts` 文件，我加个示例代码吧，可以试着参考下

**Comment by noexpect9** [comment]
好的 十分感谢😊

**Comment by pdsuwwz** [comment]
@noexpect9  加上了，看下是否是你想要的效果，如果没有问题，可关闭该 issue .

**Comment by noexpect9** [comment]
是的 非常感谢
